name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Setup Git User
        shell: bash
        run: |
          git config --global user.email "yarikrom05@gmail.com"
          git config --global user.name "Yaroslav Romanenko"

      - name: Create Release
        uses: changesets/action@v1
        with:
          publish: pnpm release
          title: "ci(changesets): :package: version packages"
          commit: "ci(changesets): version packages"
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
